name: Python application

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyinstaller
    - name: run build
      run: |
        pyinstaller --onefile EasyMulti.pyw
        ls
    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: /home/runner/work/Easy-Multi/Easy-Multi/dist/EasyMulti.exe
        draft: true
        
